export const REQUEST_FP_PENDING = "REQUEST_FP_PENDING";
export const REQUEST_FP_SUCCESS = "REQUEST_FP_SUCCESS";
export const REQUEST_FP_ERROR = "REQUEST_FP_ERROR";

export const REQUEST_RP_PENDING = "REQUEST_RP_PENDING";
export const REQUEST_RP_SUCCESS = "REQUEST_RP_SUCCESS";
export const REQUEST_RP_ERROR = "REQUEST_RP_ERROR";