export const REQUEST_SIGNIN_PENDING = "REQUEST_SIGNIN_PENDING";
export const REQUEST_SIGNIN_SUCCESS = "REQUEST_SIGNIN_SUCCESS";
export const REQUEST_SIGNIN_ERROR = "REQUEST_SIGNIN_ERROR";
export const SET_USER_ROLE = "SET_USER_ROLE"