export const REQUEST_REGISTER_PENDING = "REQUEST_REGISTER_PENDING";
export const REQUEST_REGISTER_SUCCESS = "REQUEST_REGISTER_SUCCESS";
export const REQUEST_REGISTER_ERROR = "REQUEST_REGISTER_ERROR";
