export const REQUEST_REGISTER_PENDING = "REQUEST_REGISTER_PENDING";
export const REQUEST_REGISTER_SUCCESS = "REQUEST_REGISTER_SUCCESS";
export const REQUEST_REGISTER_ERROR = "REQUEST_REGISTER_ERROR";

export const REQUEST_CONFIRMATION_PENDING = "REQUEST_CONFIRMATION_PENDING"
export const REQUEST_CONFIRMATION_SUCCESS = "REQUEST_CONFIRMATION_SUCCESS"
export const REQUEST_CONFIRMATION_ERROR = "REQUEST_CONFIRMATION_ERROR"