apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-users-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-users
  template:
    metadata:
      labels:
        app: micro-users
    spec:
      containers:
        - name: micro-users
          image: nikitkrskrecepies/micro-users
          env:
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'recepies'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name   
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: TYPEORM_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-users-secret
                  key: DB_HOST
            - name: TYPEORM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-users-secret
                  key: DB_USER
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-users-secret
                  key: DB_PASSWORD
            - name: TYPEORM_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-users-secret
                  key: DB_NAME
            - name: SMTP_API_KEY
              value: 'api-96C6B80C474611EAAFCDF23C91BBF4A0'

            
---
apiVersion: v1
kind: Service
metadata:
  name: micro-users-srv
spec:
  selector:
    app: micro-users
  ports:
    - name: micro-users
      protocol: TCP
      port: 3000
      targetPort: 3000
